spring:
  config:
    import: optional:file:.env.production[.properties]

  application:
    name: dev_demo
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  devtools:
    add-properties: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${PUBLIC_KEYCLOAK_ISSUER_URI}
  
logging:
  level:
    org.springframework: INFO

server:
  port: ${PORT}

keycloak:
  server-url: ${PUBLIC_KEYCLOAK_URL}
  realm: ${KEYCLOAK_REALM}
  admin-realm: ${KEYCLOAK_ADMIN_REALM}
  admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID}
  admin-username: ${KEYCLOAK_ADMIN_USERNAME}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD}
